export const config = {
  API_BASE_URL: import.meta.env.VITE_API_URL || 'http://localhost:8080/api',
  APP_NAME: 'सिद्धिविनायक आर्ट्स',
  APP_VERSION: '1.0.0',
  CONTACT_PHONE: '+91 98765 43210',
  CONTACT_EMAIL: 'info@siddhivinayakarts.com',
  MAX_FILE_SIZE_MB: 10,
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/jpg', 'image/webp'],
  ADMIN_WHATSAPP: '918767739911',
  DEFAULT_PAGE_SIZE: 10,
  DATE_FORMAT: 'DD-MM-YYYY',
  SHOP_LOCATION: 'https://maps.google.com/maps?q=Siddhivinayak+Arts+Pune',
  UPI_ID: 'siddhivinayakarts@upi',
  OWNER_NAME: 'श्री. सचिन पाटील',
  OWNER_PHOTO: '/owner.jpg',
  ESTABLISHED_YEAR: 1995,
};